name: danamonTest
description: Danamon Mobile Developer Test.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+200

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Common
  flutter_bloc: ^8.1.3
  go_router: ^13.1.0
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.5
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0

  # iOS
  cupertino_icons: ^1.0.2

  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  retrofit: ^4.0.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  get_secure_storage: ^1.0.4
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  dartz: ^0.10.1
  talker_flutter: ^4.0.0
  talker_dio_logger: ^4.0.0
  talker_bloc_logger: ^4.0.0
  connectivity_plus: ^5.0.2
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  app_bar_with_search_switch: ^1.7.0
  modal_bottom_sheet: ^3.0.0-pre
  supabase_flutter: ^2.3.4
  another_flushbar: ^1.12.30
  lottie: ^3.0.0
  easy_image_viewer: ^1.4.1
  flutter_native_splash: ^2.3.10
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  built_value_generator: ^8.9.0
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  freezed: ^2.4.6

scripts: derry.yaml

flutter_gen:
  output: lib/common/gen/
  assets:
    enabled: true
  integrations:
    flutter_svg: true
    lottie: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/image/logo/logo.png
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/env/
    - assets/fonts/
    - assets/image/logo/
    - assets/image/icon/
    - assets/lottie/
